### ISSUE TITLE
Brackets highlight in red sometimes

### ISSUE THREAD

**Issue by DuCosucosu** [pulkomandy/c.vim#15]
![image](https://user-images.githubusercontent.com/100367609/229364805-41e2eee5-7cf4-4556-af80-e1a04378e324.png)

**Comment by pulkomandy** [comment]
Hello, thanks for reporting!

Some observations (mainly for myself to look into this later, unless someone else wants to attempt it):
- Does not happen with rainbow parentheses plugin activated
- To get the same error as in the screenshot, you have to let g:c_no_curly_error = 1. Otherwise, the brackets for the while are highlighted in error instead
- The red highlight is from vim main c.vim, cErrInParen rule. I think (but I should check more closely) this rule is supposed to be desactivated inside {} pairs in the definition of cBlock, but the patches to c.vim do not let cBlock match, and so we need our own way to exclude this rule where innapropriate?

These tests were done with vim 8.2, which version do you use? Any other plugins that may affect the behavior? (probably not, since I can reproduce the problem)
